"use client";

import { useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, ChevronRight, CirclePlus, FolderKanban, LayoutDashboard, LibraryBig, Plus, RefreshCw, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Toaster } from "@/components/ui/sonner";

type Category = { id: number; name: string; kind: "income" | "expense"; systemKey: string | null };
type Employee = { id: number; name: string; email: string | null };
type Project = { id: number; name: string; client: string; status: string; incomeKopecks: number; expenseKopecks: number; profitKopecks: number; profitability: number | null; entryCount: number; employees: Array<{ employeeId: number; name: string }> };
type Entry = { id: number; projectId: number; categoryId: number; amountKopecks: number; operationDate: string; comment: string; authorName: string; categoryName: string; kind: "income" | "expense" };
type Dashboard = { categories: Category[]; employees: Employee[]; projects: Project[]; entries: Entry[]; overall: { incomeKopecks: number; expenseKopecks: number; profitKopecks: number; profitability: number | null } };

declare global { interface Window { BX24?: { init: (callback: () => void) => void; getAuth: () => Record<string, string> } } }
const money = new Intl.NumberFormat("ru-RU", { style: "currency", currency: "RUB", maximumFractionDigits: 2 });
const formatMoney = (kopecks: number) => money.format(kopecks / 100);
const today = new Date().toISOString().slice(0, 10);
async function api(body?: Record<string, unknown>, method = "POST") { const response = await fetch("/api/app", body ? { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : undefined); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Ошибка запроса"); return payload; }

function MetricCard({ label, value, tone, note }: { label: string; value: string; tone: string; note: string }) { return <div className="metric-card"><div className={`metric-mark ${tone}`} /><p>{label}</p><strong>{value}</strong><span>{note}</span></div>; }

export default function FinanceApp() {
  const [data, setData] = useState<Dashboard | null>(null); const [selectedId, setSelectedId] = useState<number | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [actor, setActor] = useState("Демо-пользователь"); const [bitrixConnected, setBitrixConnected] = useState(false);
  const [transactionOpen, setTransactionOpen] = useState(false); const [projectOpen, setProjectOpen] = useState(false); const [directoryOpen, setDirectoryOpen] = useState(false); const [memberOpen, setMemberOpen] = useState(false);
  const [entryForm, setEntryForm] = useState({ projectId: "", kind: "income", categoryId: "", amount: "", operationDate: today, comment: "" });
  const [projectForm, setProjectForm] = useState({ name: "", client: "", employeeIds: [] as number[] });
  const [categoryForm, setCategoryForm] = useState({ name: "", kind: "expense" }); const [employeeForm, setEmployeeForm] = useState({ name: "", email: "" }); const [memberId, setMemberId] = useState("");

  const load = async () => { try { setError(""); const next = await api(undefined, "GET") as Dashboard; setData(next); setSelectedId((current) => current && next.projects.some((p) => p.id === current) ? current : next.projects[0]?.id ?? null); } catch (e) { setError(e instanceof Error ? e.message : "Ошибка загрузки"); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (!window.BX24) return; window.BX24.init(async () => { try { const auth = window.BX24?.getAuth() || {}; const response = await fetch("/api/bitrix/sync", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ domain: auth.domain || auth.DOMAIN, accessToken: auth.access_token || auth.ACCESS_TOKEN }) }); const result = await response.json(); if (response.ok) { setActor(result.currentName || "Сотрудник Bitrix24"); setBitrixConnected(true); toast.success(`Синхронизировано сотрудников: ${result.synced}`); await load(); } } catch { /* Демо-режим остаётся рабочим. */ } }); }, []);

  const selected = data?.projects.find((p) => p.id === selectedId) ?? null;
  const selectedEntries = useMemo(() => data?.entries.filter((e) => e.projectId === selectedId) ?? [], [data, selectedId]);
  const filteredCategories = data?.categories.filter((c) => c.kind === entryForm.kind) ?? [];
  const run = async (job: () => Promise<unknown>, success: string) => { try { await job(); toast.success(success); await load(); return true; } catch (e) { toast.error(e instanceof Error ? e.message : "Ошибка"); return false; } };
  const saveEntry = async () => { const ok = await run(() => api({ action: "createEntry", ...entryForm, authorName: actor }), "Операция добавлена"); if (ok) { setTransactionOpen(false); setEntryForm({ projectId: String(selectedId ?? ""), kind: "income", categoryId: "", amount: "", operationDate: today, comment: "" }); } };
  const saveProject = async () => { const ok = await run(() => api({ action: "createProject", ...projectForm }), "Проект создан"); if (ok) { setProjectOpen(false); setProjectForm({ name: "", client: "", employeeIds: [] }); } };

  if (loading) return <main className="loading-screen"><RefreshCw className="animate-spin" /><span>Загружаем финансы проектов…</span></main>;
  if (error) return <main className="loading-screen"><strong>Не удалось открыть данные</strong><span>{error}</span><Button onClick={() => { setLoading(true); load(); }}>Повторить</Button></main>;

  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-icon"><BriefcaseBusiness /></div><div><strong>Project P&L</strong><span>для Битрикс24</span></div></div><nav><button className="active"><LayoutDashboard />Обзор</button><button onClick={() => setProjectOpen(true)}><FolderKanban />Проекты</button><button onClick={() => setDirectoryOpen(true)}><LibraryBig />Статьи и сотрудники</button></nav><div className="side-note"><span>Рентабельность</span><strong>(Прибыль ÷ Доход) × 100%</strong><p>Все суммы сохраняются в копейках — без ошибок округления.</p></div><div className="profile"><div className="avatar">{actor.slice(0, 1)}</div><div><strong>{actor}</strong><span>{bitrixConnected ? "Подключено к порталу" : "Демо-режим"}</span></div></div></aside>
    <main className="workspace"><header><div><p className="eyebrow">Финансовый центр</p><h1>Экономика проектов</h1></div><div className="header-actions"><Button variant="outline" onClick={() => setProjectOpen(true)}><Plus />Новый проект</Button><Button className="accent-button" disabled={!data?.projects.length} onClick={() => { setEntryForm((f) => ({ ...f, projectId: String(selectedId ?? data?.projects[0]?.id ?? "") })); setTransactionOpen(true); }}><CirclePlus />Добавить операцию</Button></div></header>
      <section className="metrics"><MetricCard label="Доходы" value={formatMoney(data!.overall.incomeKopecks)} tone="income" note="по всем проектам" /><MetricCard label="Расходы" value={formatMoney(data!.overall.expenseKopecks)} tone="expense" note="по всем статьям" /><MetricCard label="Прибыль" value={formatMoney(data!.overall.profitKopecks)} tone={data!.overall.profitKopecks >= 0 ? "profit" : "expense"} note="доходы минус расходы" /><MetricCard label="Рентабельность" value={data!.overall.profitability === null ? "—" : `${data!.overall.profitability.toFixed(1)}%`} tone="margin" note="доля прибыли в доходе" /></section>
      {!data!.projects.length ? <section className="empty-state"><div><FolderKanban /></div><h2>Создайте первый проект</h2><p>Или загрузите демонстрационные данные, чтобы сразу проверить расчёты и интерфейс.</p><div><Button onClick={() => setProjectOpen(true)}>Создать проект</Button><Button variant="outline" onClick={() => run(() => api({ action: "seedDemo" }), "Демо-данные загружены")}>Загрузить демо</Button></div></section> : <section className="content-grid"><div className="project-panel panel"><div className="panel-head"><div><h2>Проекты</h2><span>{data!.projects.length} в работе</span></div><Button size="icon-sm" variant="ghost" aria-label="Создать проект" onClick={() => setProjectOpen(true)}><Plus /></Button></div><div className="project-list">{data!.projects.map((project) => { const max = Math.max(project.incomeKopecks, project.expenseKopecks, 1); return <button key={project.id} className={selectedId === project.id ? "project-card selected" : "project-card"} onClick={() => setSelectedId(project.id)}><div className="project-title"><div><strong>{project.name}</strong><span>{project.client || "Без клиента"}</span></div><ChevronRight /></div><div className="project-money"><span>Прибыль</span><strong className={project.profitKopecks < 0 ? "negative" : ""}>{formatMoney(project.profitKopecks)}</strong></div><div className="mini-bars"><i style={{ width: `${project.incomeKopecks / max * 100}%` }} /><b style={{ width: `${project.expenseKopecks / max * 100}%` }} /></div><div className="project-meta"><span>{project.profitability === null ? "Нет доходов" : `${project.profitability.toFixed(1)}% рентабельность`}</span><span>{project.entryCount} операций</span></div></button>; })}</div></div>
        {selected && <div className="detail-panel panel"><div className="detail-head"><div><p className="eyebrow">{selected.client || "Внутренний проект"}</p><h2>{selected.name}</h2><div className="team">{selected.employees.slice(0, 4).map((e) => <span title={e.name} key={e.employeeId}>{e.name.split(" ").map((x) => x[0]).join("").slice(0, 2)}</span>)}<button onClick={() => setMemberOpen(true)} aria-label="Добавить сотрудника"><Plus /></button><small>{selected.employees.length ? selected.employees.map((e) => e.name).join(", ") : "Команда не назначена"}</small></div></div><Badge variant="secondary">Активен</Badge></div><div className="project-summary"><div><span>Доходы</span><strong className="green">{formatMoney(selected.incomeKopecks)}</strong></div><div><span>Расходы</span><strong className="red">{formatMoney(selected.expenseKopecks)}</strong></div><div><span>Прибыль</span><strong>{formatMoney(selected.profitKopecks)}</strong></div><div><span>Рентабельность</span><strong>{selected.profitability === null ? "—" : `${selected.profitability.toFixed(1)}%`}</strong></div></div><div className="operations-head"><div><h3>Операции</h3><span>Последние записи по проекту</span></div><Button size="sm" onClick={() => { setEntryForm((f) => ({ ...f, projectId: String(selected.id) })); setTransactionOpen(true); }}><Plus />Добавить</Button></div><Table><TableHeader><TableRow><TableHead>Дата</TableHead><TableHead>Статья</TableHead><TableHead>Комментарий</TableHead><TableHead>Автор</TableHead><TableHead className="text-right">Сумма</TableHead><TableHead /></TableRow></TableHeader><TableBody>{selectedEntries.map((entry) => <TableRow key={entry.id}><TableCell>{new Date(`${entry.operationDate}T00:00:00`).toLocaleDateString("ru-RU")}</TableCell><TableCell><span className={`kind-dot ${entry.kind}`} />{entry.categoryName}</TableCell><TableCell className="comment-cell">{entry.comment || "—"}</TableCell><TableCell>{entry.authorName}</TableCell><TableCell className={`text-right amount ${entry.kind}`}>{entry.kind === "expense" ? "−" : "+"}{formatMoney(entry.amountKopecks)}</TableCell><TableCell><Button size="icon-xs" variant="ghost" aria-label="Удалить операцию" onClick={() => run(async () => { const res = await fetch(`/api/app?id=${entry.id}`, { method: "DELETE" }); const p = await res.json(); if (!res.ok) throw new Error(p.error); }, "Операция удалена")}><Trash2 /></Button></TableCell></TableRow>)}{!selectedEntries.length && <TableRow><TableCell colSpan={6} className="empty-row">Операций пока нет</TableCell></TableRow>}</TableBody></Table></div>}</section>}
    </main>

    <Dialog open={transactionOpen} onOpenChange={setTransactionOpen}><DialogContent><DialogHeader><DialogTitle>Новая операция</DialogTitle><DialogDescription>Доход или расход будет сразу учтён в показателях проекта.</DialogDescription></DialogHeader><div className="form-grid"><div><Label>Проект</Label><Select value={entryForm.projectId} onValueChange={(v) => setEntryForm({ ...entryForm, projectId: v })}><SelectTrigger className="w-full"><SelectValue placeholder="Выберите проект" /></SelectTrigger><SelectContent>{data!.projects.map((p) => <SelectItem key={p.id} value={String(p.id)}>{p.name}</SelectItem>)}</SelectContent></Select></div><div className="two-col"><div><Label>Тип</Label><Select value={entryForm.kind} onValueChange={(v) => setEntryForm({ ...entryForm, kind: v, categoryId: "" })}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="income">Доход</SelectItem><SelectItem value="expense">Расход</SelectItem></SelectContent></Select></div><div><Label>Статья</Label><Select value={entryForm.categoryId} onValueChange={(v) => setEntryForm({ ...entryForm, categoryId: v })}><SelectTrigger className="w-full"><SelectValue placeholder="Выберите" /></SelectTrigger><SelectContent>{filteredCategories.map((c) => <SelectItem key={c.id} value={String(c.id)}>{c.name}</SelectItem>)}</SelectContent></Select></div></div><div className="two-col"><div><Label htmlFor="amount">Сумма, ₽</Label><Input id="amount" inputMode="decimal" placeholder="0,00" value={entryForm.amount} onChange={(e) => setEntryForm({ ...entryForm, amount: e.target.value })} /></div><div><Label htmlFor="date">Дата</Label><Input id="date" type="date" value={entryForm.operationDate} onChange={(e) => setEntryForm({ ...entryForm, operationDate: e.target.value })} /></div></div><div><Label htmlFor="comment">Комментарий</Label><Textarea id="comment" placeholder="За что получен доход или понесён расход" value={entryForm.comment} onChange={(e) => setEntryForm({ ...entryForm, comment: e.target.value })} /></div></div><DialogFooter><Button variant="outline" onClick={() => setTransactionOpen(false)}>Отмена</Button><Button onClick={saveEntry}>Сохранить операцию</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={projectOpen} onOpenChange={setProjectOpen}><DialogContent><DialogHeader><DialogTitle>Новый проект</DialogTitle><DialogDescription>Команду можно изменить и после создания.</DialogDescription></DialogHeader><div className="form-grid"><div><Label htmlFor="project-name">Название</Label><Input id="project-name" value={projectForm.name} onChange={(e) => setProjectForm({ ...projectForm, name: e.target.value })} placeholder="Например, Корпоративный портал" /></div><div><Label htmlFor="client">Клиент</Label><Input id="client" value={projectForm.client} onChange={(e) => setProjectForm({ ...projectForm, client: e.target.value })} placeholder="Необязательно" /></div><div><Label>Сотрудники проекта</Label><div className="check-list">{data!.employees.map((e) => <label key={e.id}><Checkbox checked={projectForm.employeeIds.includes(e.id)} onCheckedChange={(checked) => setProjectForm({ ...projectForm, employeeIds: checked ? [...projectForm.employeeIds, e.id] : projectForm.employeeIds.filter((id) => id !== e.id) })} /><span>{e.name}<small>{e.email}</small></span></label>)}{!data!.employees.length && <p>Добавьте сотрудников в справочнике.</p>}</div></div></div><DialogFooter><Button variant="outline" onClick={() => setProjectOpen(false)}>Отмена</Button><Button onClick={saveProject}>Создать</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={directoryOpen} onOpenChange={setDirectoryOpen}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>Статьи и сотрудники</DialogTitle><DialogDescription>Системные статьи уже добавлены. Ниже можно расширить справочники.</DialogDescription></DialogHeader><div className="directory-grid"><section><h3>Новая статья</h3><Input placeholder="Название статьи" value={categoryForm.name} onChange={(e) => setCategoryForm({ ...categoryForm, name: e.target.value })} /><Select value={categoryForm.kind} onValueChange={(v) => setCategoryForm({ ...categoryForm, kind: v })}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="income">Доход</SelectItem><SelectItem value="expense">Расход</SelectItem></SelectContent></Select><Button onClick={async () => { if (await run(() => api({ action: "createCategory", ...categoryForm }), "Статья добавлена")) setCategoryForm({ name: "", kind: "expense" }); }}>Добавить статью</Button><div className="chips">{data!.categories.map((c) => <span key={c.id} className={c.kind}>{c.name}</span>)}</div></section><section><h3>Новый сотрудник</h3><Input placeholder="Имя и фамилия" value={employeeForm.name} onChange={(e) => setEmployeeForm({ ...employeeForm, name: e.target.value })} /><Input placeholder="Рабочая почта" value={employeeForm.email} onChange={(e) => setEmployeeForm({ ...employeeForm, email: e.target.value })} /><Button onClick={async () => { if (await run(() => api({ action: "createEmployee", ...employeeForm }), "Сотрудник добавлен")) setEmployeeForm({ name: "", email: "" }); }}>Добавить сотрудника</Button><div className="people-list">{data!.employees.map((e) => <div key={e.id}><span>{e.name.slice(0, 1)}</span><p><strong>{e.name}</strong><small>{e.email || "Без почты"}</small></p></div>)}</div></section></div></DialogContent></Dialog>
    <Dialog open={memberOpen} onOpenChange={setMemberOpen}><DialogContent><DialogHeader><DialogTitle>Добавить сотрудника</DialogTitle><DialogDescription>{selected?.name}</DialogDescription></DialogHeader><Select value={memberId} onValueChange={setMemberId}><SelectTrigger className="w-full"><SelectValue placeholder="Выберите сотрудника" /></SelectTrigger><SelectContent>{data!.employees.filter((e) => !selected?.employees.some((m) => m.employeeId === e.id)).map((e) => <SelectItem key={e.id} value={String(e.id)}>{e.name}</SelectItem>)}</SelectContent></Select><DialogFooter><Button variant="outline" onClick={() => setMemberOpen(false)}>Отмена</Button><Button disabled={!memberId} onClick={async () => { if (await run(() => api({ action: "addMember", projectId: selectedId, employeeId: memberId }), "Сотрудник добавлен")) { setMemberOpen(false); setMemberId(""); } }}>Добавить</Button></DialogFooter></DialogContent></Dialog><Toaster richColors position="top-right" />
  </div>;
}
